No1 = input("(1/10) Noun=")
No2 = input("(2/10) Adjective=")
No3 = input("(3/10) Verb ending in s=")
No4 = input("(4/10) PluNoun=")
No5 = input("(5/10) Action ending in s=")
No6 = input("(6/10) Verb ending in ing=")
No7 = input("(7/10) Verb=")
No8 = input("(8/10) Place=")
No9 = input("(9/10) Action ending in ing=")
No10 = input("(10/10) Noun ending in s -thing-=")
print("%s is/are very %s that %s %s and %s with people after %s. It's also very %s to out to %s and go %s and asking "
      "strangers for %s." % (No1, No2, No3, No4, No5, No6, No7, No8, No9, No10))
